apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  ports: 8080
  - nodePort: 30080
    port: 8080
    targetPort: 8080
  selector:
    name: simple-webapp
  type: --ipCluster is the default type of any service so even if we dont specify the value explicitly it will be applied as deafult service type
